"""AMRO 三域同步编排包（飞机 / 工作包 / 工卡版本，只读、零快照）。

子模块：query_runner / aircraft / packages / versions；本文件重导出全部公开符号，
外部 `from reqman.services import amro_sync` 与 `amro_sync.<symbol>` 调用方式不变。
"""
__all__ = (
    "AMRO_AC_FLEET",
    "AMRO_CARD_FLEET",
    "AMRO_FLA_PLUGIN",
    "CATEGORY_ORDER",
    "CHECK_TEMPLATE_FILE",
    "OUTPUT_DIR",
    "QUERY_STATUS",
    "QueryBusyError",
    "_aircraft_fields",
    "_collect_card_versions",
    "_family_of",
    "_get_entity_by_jcno",
    "_group_by_category",
    "_is_in_scope",
    "_item_from_row",
    "_last_package_query",
    "_main_squadron",
    "_move_to_cancelled",
    "_norm_reg",
    "_package_header",
    "_pull_amro_family",
    "_pull_smjc_versions",
    "_version_summary",
    "_wd",
    "_ymd_date",
    "amro",
    "build_package_label",
    "build_version_report_excel",
    "check_cards_against_amro",
    "end_query",
    "full_version_check",
    "get_last_package_query",
    "get_last_query_result",
    "get_query_status",
    "import_amro_package",
    "list_amro_packages",
    "package_items",
    "persist_amro_package",
    "query_busy_message",
    "query_slot",
    "require_amro_session",
    "run_query",
    "save_last_query_result",
    "start_aircraft_sync",
    "start_full_version_check",
    "start_inventory_query",
    "start_package_version_check",
    "sync_aircraft",
    "try_begin_query",
)
from ...config import (
    AMRO_AC_FLEET,
    AMRO_CARD_FLEET,
    CATEGORY_ORDER,
    CHECK_TEMPLATE_FILE,
    OUTPUT_DIR,
)
from ..connectors import amro
from .aircraft import (
    _aircraft_fields,
    _norm_reg,
    start_aircraft_sync,
    sync_aircraft,
)
from .packages import (
    _item_from_row,
    _last_package_query,
    _main_squadron,
    _package_header,
    build_package_label,
    get_last_package_query,
    import_amro_package,
    list_amro_packages,
    package_items,
    persist_amro_package,
)
from .query_runner import (
    QUERY_STATUS,
    QueryBusyError,
    end_query,
    get_last_query_result,
    get_query_status,
    query_busy_message,
    query_slot,
    require_amro_session,
    run_query,
    save_last_query_result,
    try_begin_query,
)
from .versions import (
    AMRO_FLA_PLUGIN,
    _collect_card_versions,
    _family_of,
    _get_entity_by_jcno,
    _group_by_category,
    _is_in_scope,
    _move_to_cancelled,
    _pull_amro_family,
    _pull_smjc_versions,
    _version_summary,
    _wd,
    _ymd_date,
    build_version_report_excel,
    check_cards_against_amro,
    full_version_check,
    start_full_version_check,
    start_inventory_query,
    start_package_version_check,
)
